version: '3.8'

services:
  backend_v2:
    build: .
    container_name: backend_v2
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017
      - MONGODB_DATABASE=cbt_protocols_v2
      - PORT=8081
      - GIN_MODE=release
      - API_KEY=${API_KEY:-your-api-key-here}
      - HEARTBEAT_TIMEOUT=60
      - CLEANUP_INTERVAL=300
    depends_on:
      - mongodb
    networks:
      - cbt_network

  mongodb:
    image: mongo:6.0
    container_name: backend_v2_mongodb
    restart: unless-stopped
    ports:
      - "27018:27017"  # Different port to avoid conflict with existing MongoDB
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=cbt_protocols_v2
    networks:
      - cbt_network

volumes:
  mongodb_data:

networks:
  cbt_network:
    driver: bridge 